### ISSUE TITLE
VSCode-like "Go to definition"

### ISSUE THREAD

**Issue by ElieCaratge** [annepinson/free-pizza#3]
I'd like someting similar to `f12` mapping in vscode :

- Go to source definition
- View usages

And for all language servers

**Comment by annepinson** [comment]
Should be added in commit "jump to definiton + replace in all files + fucking doc", I"ll let you see if it corresponds to your wish

**Comment by annepinson** [comment]
The mapping is `gf` or `gd` or `gt` according to the split you prefer
